/*
 * JOPA
 * Copyright (C) 2024 Czech Technical University in Prague
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3.0 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library.
 */
package cz.cvut.kbss.jopa.proxy.reference;

import cz.cvut.kbss.jopa.model.descriptors.Descriptor;
import cz.cvut.kbss.jopa.sessions.UnitOfWork;

import java.net.URI;

/**
 * Provides access to persistence context-related attributes needed by entity reference proxies.
 * <p>
 * This interface should be implemented by the classes generated by {@link EntityReferenceProxyGenerator}.
 */
public interface EntityReferenceProxyPropertyAccessor<T> {

    URI getIdentifier();

    void setIdentifier(URI identifier);

    Class<T> getType();

    void setType(Class<T> entityType);

    Descriptor getDescriptor();

    void setDescriptor(Descriptor descriptor);

    UnitOfWork getPersistenceContext();

    void setPersistenceContext(UnitOfWork uow);

    T getValue();

    void setValue(T value);
}
