package cz.cvut.kbss.jopa.proxy.reference;

import cz.cvut.kbss.jopa.model.descriptors.Descriptor;
import cz.cvut.kbss.jopa.sessions.UnitOfWork;

import java.net.URI;

/**
 * Provides access to persistence context-related attributes needed by entity reference proxies.
 * <p>
 * This interface should be implemented by the classes generated by {@link EntityReferenceProxyGenerator}.
 */
public interface EntityReferenceProxyPropertyAccessor<T> {

    URI getIdentifier();

    void setIdentifier(URI identifier);

    Class<T> getType();

    void setType(Class<T> entityType);

    Descriptor getDescriptor();

    void setDescriptor(Descriptor descriptor);

    UnitOfWork getPersistenceContext();

    void setPersistenceContext(UnitOfWork uow);

    T getValue();

    void setValue(T value);
}
