
package cz.cvut.kbss.failures.model;

import java.util.Map;
import java.util.Set;
import cz.cvut.kbss.failures.Vocabulary;
import cz.cvut.kbss.jopa.CommonVocabulary;
import cz.cvut.kbss.jopa.model.annotations.Id;
import cz.cvut.kbss.jopa.model.annotations.OWLAnnotationProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLDataProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import cz.cvut.kbss.jopa.model.annotations.Properties;
import cz.cvut.kbss.jopa.model.annotations.Types;


/**
 * This class was generated by the OWL2Java tool version 0.2
 * 
 */
@OWLClass(iri = Vocabulary.s_c_GPSPosition)
public class GPSPosition {

    @OWLAnnotationProperty(iri = CommonVocabulary.RDFS_LABEL)
    protected String label;
    @Types
    protected Set<String> types;
    @Id(generated = true)
    protected String id;
    @Properties
    protected Map<String, Set<String>> properties;
    @OWLDataProperty(iri = Vocabulary.s_p_hasAltitude)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_d_double, min = 1, max = 1)
    })
    protected Double hasAltitude;
    @OWLDataProperty(iri = Vocabulary.s_p_hasLongitude)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_d_double, min = 1, max = 1)
    })
    protected Double hasLongitude;
    @OWLDataProperty(iri = Vocabulary.s_p_hasLatitude)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_d_double, min = 1, max = 1)
    })
    protected Double hasLatitude;

    public void setLabel(String label) {
        this.label = label;
    }

    public String getLabel() {
        return label;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setProperties(Map<String, Set<String>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<String>> getProperties() {
        return properties;
    }

    public void setHasAltitude(Double hasAltitude) {
        this.hasAltitude = hasAltitude;
    }

    public Double getHasAltitude() {
        return hasAltitude;
    }

    public void setHasLongitude(Double hasLongitude) {
        this.hasLongitude = hasLongitude;
    }

    public Double getHasLongitude() {
        return hasLongitude;
    }

    public void setHasLatitude(Double hasLatitude) {
        this.hasLatitude = hasLatitude;
    }

    public Double getHasLatitude() {
        return hasLatitude;
    }

}
