package cz.cvut.kbss.jopa.example01;

public class Example {

    private static final String MANUAL = "manual";
    private static final String GENERATED = "generated";

    public static void main(String[] args) {
        if (args.length < 1) {
            System.err.println("Missing example type argument.");
            printUsageInfo();
            System.exit(1);
        }
        final String command = args[0];
        Runner runner = null;
        switch (command) {
            case MANUAL:
                runner = new ManualRunner();
                break;
            case GENERATED:
                runner = new GeneratedRunner();
                break;
            default:
                printUsageInfo();
                break;
        }
        if (runner != null) {
            runner.run();
        }
    }

    private static void printUsageInfo() {
        System.out.println("Possible arguments: ");
        System.out.println("   '" + MANUAL + "'     - Executes the demo with manually written data model.");
        System.out.println("   '" + GENERATED + "'  - Executes the demo with data model generated by OWL2Java.");
    }
}
